### ISSUE TITLE
Roadmap for GemGIS 1.0

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gemgis#14]
A roadmap for GemGIS:

**What is the aim of GemGIS?** 
Providing a way to interactively select/add/edit/delete input data of all kinds that is needed for GemPy. Make it easy for beginners to build a first model (geological knowledge and some coding expected). 

**What do we need for that?**
- A tool to display map data and to interactively select and store data automatically. It should be easy and intuitively to handle. A very important aspect is that we avoid changing/protecting existing data unless you want to and that it is easier to add data for a particular surface, similar to editing features in QGIS rather than filling out the table maybe. 

- [x]  Simple vector and raster manipulation tools in the background of GemGIS, especially reprojection of data.

- [x] Extraction of points/vertices from rasters and vector files.

- [x] Ability to import styles from QGIS to color your data.

- [ ] Maybe some statistic tools or plots such as the frequency of selected interfaces for each surface or stereonets (partly possible with GemPy already).

- [x] Ability to georeference geological maps (setting the extent of an array in its simplest form) for point selection afterwards - https://rasterio.readthedocs.io/en/latest/topics/georeferencing.html 

- [x] Ability to create a topography based on digitized contour lines or a line shape file. 

(The last two points could be interesting for teaching purposes where students could digitize a map and create a GemPy model afterwards)

- [x] The output of GemGIS could be a data object containing different attributes such as the crs, the extent, the interfaces, orientations, custom_sections, the topography, the layer stack etc. which could directly be passed to GemPy to create a model.

**Which tools do we have already?**
- Vector files - [GeoPandas](https://geopandas.org/index.html) 
- Raster files - [Rasterio](https://rasterio.readthedocs.io/en/latest/#) 
- Reprojection of data - [PyProj](https://pyproj4.github.io/pyproj/stable/) 
- WMS data - [OWSLib](https://geopython.github.io/OWSLib/) 
- DataFrames - [Pandas](https://pandas.pydata.org/) 
-  [Bokeh](https://docs.bokeh.org/en/latest/index.html) (proved the concept), [ipyleaflet](https://ipyleaflet.readthedocs.io/en/latest/)  (missing interactivity), [Dash/Plotly](https://plotly.com/dash/)  (needs to be tested)

![image](https://user-images.githubusercontent.com/45469915/84598579-0ca40c00-ae6c-11ea-9852-e23e0a53b605.png)

**Comment by endarthur** [comment]
In addition to that, GemGIS could also work as a bridge between QGIS and GemPy. Most features needed for that are already covered in the roadmap, that is:

- Reprojection to a given CRS
- Vertices extraction, in case of lines and polygons as input data
- QGIS styling parsing

And the GemGIS output data object in general. That would allow having either a notebook open on which you could rerun a cell to update the model or some sort of standalone script that could auto update on detecting changes to the input shapefiles or configuration.

Another possible integration would be to export GemPy's geological map as a shapefile or some other GIS format, so that it could  be opened on QGIS.

**Comment by AlexanderJuestel** [comment]
Will be closed in favor of an updated roadmap in the future.
