### ISSUE TITLE
Code Samples and Examples that could be provided for GemPy/GemGIS after the thesis

### ISSUE THREAD

**Issue by AlexanderJuestel** [cgre-aachen/gemgis#62]
This is a list of examples that I would like to provide to the GemPy project after my thesis:

- [x]  Function to create depth maps for a single surface - Implemented in GemGIS

- [ ] Example on how to draw random values from a von Mises Fisher Distribution (based on the works of @elimh and help of @Japhiolite :)). I may also be considered reworking fishdist.py due to an outdated spherecluster package - cgre-aachen/gempy#30, cgre-aachen/gemgis#38, cgre-aachen/gempy#475  

- [x] Example of a simple model of a fold and thrust belt for the Sphinx gallery

- [x] Example/Tutorial on how to get larger datasets more efficiently into GemPy utilizing the capabilities of GeoPandas and Rasterio (working with spatial data) and later hopefully with GemGIS - Implemented in GemGIS

- [x] Model of my thesis as "PyVista Project" -> providing the vertices and edges to calculate meshes and view the model in PyVista, no input data though

- [x] Function to extract a vertical synthetic borehole - Implemented in GemGIS

- [x] Prepare Kartenkunde Examples as GemPy Model - currently done in GemGIS

- [x] Create GemPy models from cross-sections of von Winterfeld (1994) and Ribbert et Wrede (2005)

- [x] Create animations from Cross Sections - See Elisa's Notebook

- [x] Create 2D plot of cross-sections cgre-aachen/gemgis#35 

- [x] Create 3D plot of cross sections cgre-aachen/gemgis#36 

- [x] Create 3D plot of Uncertainties and Information Entropy 

- [x] Function to plot well paths in PyVista according to lithology and plotting well logs with the radius of the well as a function of a log value

More examples to come maybe :)
